dist: trusty
sudo: false

language: python
python: "3.5"

cache: pip

# Python 3.6 is not installed by default so...
before_install:
  - pyenv install 3.6.0a3
  - pyenv versions
  - which python2.7
  - which python3.3
  - which python3.4
  - which python3.5
  - which python3.6

install:
  - pip install coverage detox

script:
  - coverage erase
  - detox

after_success:
  - coverage combine --append
  - coverage report -m
